scrapper:
  test: 1
  scheduler:
    interval: 50000
  update-frequency: 30
  access-type: jpa
  use-queue: true

server:
  port: 8082

rabbit:
  queue-name: "update-notify-queue"
  exchange-name: "update-notify-exchange"
  routing-key: "update_request"


clients:
  base-url:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com/2.3
    bot: http://localhost:8081

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: false

  liquibase:
    enabled: false

  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672

springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui