scrapper:
  test: 1
  scheduler:
    interval: 50000
  update-frequency: 30

server:
  port: 8082

clients:
  base-url:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com/2.3
    bot: http://localhost:8081

spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  liquibase:
    enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui