scrapper:
  test:
    1
  scheduler:
    interval:
      10000

clients:
  base-url:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com/2.3

spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}

springdoc:
  api-docs:
    enables: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui