bot:
  test: 1
  telegram-token: ${TELEGRAM-TOKEN}
  base-url-scrapper: http://localhost:8082

server:
  port: 8081

rabbit:
  queue-name: "update-notify-queue"
  exchange-name: "update-notify-exchange"
  routing-key: "update_request"

springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false