name: build-bot

on:
  push:
    paths:
      - '.github/workflows/bot.yml'
      - 'bot/**'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: maven

      - name: Check style scrapper and link parser
        run: mvn -pl bot -am checkstyle:check

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: maven

      - name: Maven package jar bot
        run: mvn package -pl bot -am

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: cd bot && docker build -f Dockerfile -t ghcr.io/${{ github.repository }}/bot:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/bot:latest
