global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'bot-scrapper'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - host.docker.internal:8083
          - host.docker.internal:8084
